- hosts: all
  become: true
  tasks:
  
    - name: Pull calculator docker image
      community.docker.docker_image:
        name: sjtpy/calculator
        source: pull

    - name: Launch the calculator container
      docker_container:
        name: calculator
        image: sjtpy/calculator
        state: started
        
